# Generated by Django 3.0.8 on 2020-09-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
